### ISSUE TITLE
spatialite compilation

### ISSUE THREAD

**Issue by dthib** [Smartrak/SpatialiteSharp#1]
Hi,

Thank you for your code, it is really helpful.  

Actually, I was trying to do the same thing but I get an AcessViolation exception when I try to do a spatial query with my spatialite dll. But the loadextension method is ok.

This is not the case with your mod-spatialite dll. Can you tell me how did you compile it? (Which version, Amalgamation, compilation options...).

Thank you for your help,
Best regards,
Thibaut

**Comment by danzel** [comment]
Downloaded them from the spatialite website:
http://www.gaia-gis.it/gaia-sins/

http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-4.2.0-win-amd64.7z

**Comment by dthib** [comment]
Sounds weird but i did not try the mod package but all the others :) Thanks for the details! I took a look at the website and now I got the difference.
Best,
Thibaut
